"""
Main application for Spotify Recommender System.
"""
from spotify_token import get_spotify_client
from data_collector import DataCollector
from recommender import SpotifyRecommender
import argparse
import json


def print_track(track: dict, index: int = None):
    """Pretty print a track."""
    prefix = f"{index}. " if index is not None else ""
    artists = ", ".join(track.get('artists', []))
    print(f"{prefix}{track.get('name', 'Unknown')} - {artists}")


def print_recommendations(recommendations: list, title: str = "Recommendations"):
    """Print a list of recommendations."""
    print(f"\n{'='*60}")
    print(f"{title}")
    print(f"{'='*60}")
    
    if not recommendations:
        print("No recommendations found.")
        return
    
    for idx, track in enumerate(recommendations, 1):
        print_track(track, idx)
    
    print(f"\nTotal: {len(recommendations)} tracks")


def create_recommendation_playlist(
    recommender: SpotifyRecommender,
    tracks: list,
    playlist_name: str = "Recommended Tracks"
) -> str:
    """Create a Spotify playlist with recommended tracks."""
    sp = recommender.sp
    user_id = sp.current_user()["id"]
    
    # Create playlist
    playlist = sp.user_playlist_create(
        user_id,
        playlist_name,
        public=False,
        description="Generated by Spotify Recommender System"
    )
    
    playlist_id = playlist["id"]
    
    # Add tracks (max 100 at a time)
    track_uris = [track['uri'] for track in tracks if track.get('uri')]
    
    for i in range(0, len(track_uris), 100):
        batch = track_uris[i:i+100]
        sp.playlist_add_items(playlist_id, batch)
    
    print(f"\n✓ Created playlist: {playlist_name}")
    print(f"  Playlist ID: {playlist_id}")
    print(f"  Spotify URL: {playlist['external_urls']['spotify']}")
    
    return playlist_id


def main():
    parser = argparse.ArgumentParser(description="Spotify Recommender System")
    parser.add_argument(
        '--mode',
        choices=['content', 'spotify', 'hybrid', 'artist', 'similar-artists'],
        default='hybrid',
        help='Recommendation mode'
    )
    parser.add_argument(
        '--seed-tracks',
        nargs='+',
        help='Seed track names or IDs (for content/hybrid modes)'
    )
    parser.add_argument(
        '--seed-artist',
        type=str,
        help='Seed artist name (for artist mode)'
    )
    parser.add_argument(
        '--limit',
        type=int,
        default=20,
        help='Number of recommendations (default: 20)'
    )
    parser.add_argument(
        '--create-playlist',
        action='store_true',
        help='Create a Spotify playlist with recommendations'
    )
    parser.add_argument(
        '--playlist-name',
        type=str,
        default='Recommended Tracks',
        help='Name for the created playlist'
    )
    parser.add_argument(
        '--collect-data',
        action='store_true',
        help='Collect and display user listening data'
    )
    
    args = parser.parse_args()
    
    # Initialize Spotify client
    print("Connecting to Spotify...")
    sp = get_spotify_client()
    print(f"✓ Authenticated as: {sp.current_user()['display_name']}\n")
    
    # Initialize components
    collector = DataCollector(sp)
    recommender = SpotifyRecommender(sp)
    
    # Collect user data if requested
    if args.collect_data:
        user_data = collector.collect_user_data()
        print("\n" + "="*60)
        print("Your Listening Data Summary")
        print("="*60)
        print(f"Saved Tracks: {len(user_data['saved_tracks'])}")
        print(f"Recently Played: {len(user_data['recent_tracks'])}")
        print(f"Playlists: {len(user_data['playlists'])}")
        
        if user_data['playlists']:
            print("\nTop Playlists:")
            for pl in user_data['playlists'][:5]:
                print(f"  - {pl['name']} ({pl['tracks_count']} tracks)")
        
        return
    
    # Get user's saved tracks for context
    print("Loading your saved tracks...")
    # API limit is 50 per request, but method paginates to get all tracks
    user_tracks = collector.get_saved_tracks(limit=50)
    
    recommendations = []
    
    if args.mode == 'content':
        if not args.seed_tracks:
            print("Error: --seed-tracks required for content-based recommendations")
            return
        
        # Find seed tracks in user's library
        seed_tracks = []
        for seed in args.seed_tracks:
            # Try to find by name
            for track in user_tracks:
                if seed.lower() in track['name'].lower():
                    seed_tracks.append(track)
                    break
        
        if not seed_tracks:
            print("Error: Could not find seed tracks in your library")
            return
        
        recommendations = recommender.content_based_recommendations(
            seed_tracks=seed_tracks,
            user_tracks=user_tracks,
            num_recommendations=args.limit
        )
        
        print_recommendations(recommendations, "Content-Based Recommendations")
    
    elif args.mode == 'spotify':
        if not args.seed_tracks:
            print("Error: --seed-tracks required for Spotify recommendations")
            return
        
        # Search for seed tracks
        seed_ids = []
        for seed in args.seed_tracks[:5]:
            results = sp.search(q=seed, type='track', limit=1)
            if results['tracks']['items']:
                seed_ids.append(results['tracks']['items'][0]['id'])
        
        if not seed_ids:
            print("Error: Could not find seed tracks")
            return
        
        recommendations = recommender.get_spotify_recommendations(
            seed_tracks=seed_ids,
            limit=args.limit
        )
        
        print_recommendations(recommendations, "Spotify API Recommendations")
    
    elif args.mode == 'hybrid':
        if not args.seed_tracks:
            print("Error: --seed-tracks required for hybrid recommendations")
            return
        
        # Find seed tracks
        seed_tracks = []
        for seed in args.seed_tracks:
            for track in user_tracks:
                if seed.lower() in track['name'].lower():
                    seed_tracks.append(track)
                    break
        
        if not seed_tracks:
            print("Error: Could not find seed tracks in your library")
            return
        
        recommendations = recommender.hybrid_recommendations(
            seed_tracks=seed_tracks,
            user_tracks=user_tracks,
            num_recommendations=args.limit
        )
        
        print_recommendations(recommendations, "Hybrid Recommendations")
    
    elif args.mode == 'artist':
        if not args.seed_artist:
            print("Error: --seed-artist required for artist recommendations")
            return
        
        recommendations = recommender.get_artist_recommendations(
            artist_name=args.seed_artist,
            limit=args.limit
        )
        
        print_recommendations(recommendations, f"Recommendations based on {args.seed_artist}")
    
    elif args.mode == 'similar-artists':
        if not args.seed_artist:
            print("Error: --seed-artist required for similar artists")
            return
        
        similar = recommender.discover_similar_artists(
            artist_name=args.seed_artist,
            limit=args.limit
        )
        
        print(f"\n{'='*60}")
        print(f"Artists Similar to {args.seed_artist}")
        print(f"{'='*60}")
        
        for idx, artist in enumerate(similar, 1):
            genres = ", ".join(artist.get('genres', [])[:3])
            print(f"{idx}. {artist['name']} (Popularity: {artist['popularity']})")
            if genres:
                print(f"   Genres: {genres}")
        
        return
    
    # Create playlist if requested
    if args.create_playlist and recommendations:
        try:
            create_recommendation_playlist(
                recommender,
                recommendations,
                args.playlist_name
            )
        except Exception as e:
            print(f"\nError creating playlist: {e}")
            print("Make sure you have the 'playlist-modify-public' or 'playlist-modify-private' scope")


if __name__ == "__main__":
    main()

